### ISSUE TITLE
¿Cómo organizar javaScript en frontend?

### ISSUE THREAD

**Issue by didaquis** [nucliweb/ama#3]
Hola. 

Imaginemos que tenemos una aplicación web que se renderiza desde el servidor (Node.js) usando Pug, EJS o cualquier otro sistema similar. Imaginemos que nuestro frontend tiene bastantes JavaScript (socket.io, listeners, etc) pero no estamos usando Webpack, ni Parcel, etc. Mi duda es la siguiente: ¿cómo debemos organizar nuestro JavaScript del frontend en un entorno de este tipo? ¿Que hacemos cuando heredamos una aplicación con 5000 lineas de JavaScript en el frontend y queremos organizar dicho caos?

¿Puedes aportar algún enlace de ejemplo?

**Comment by CKGrafico** [comment]
Buenas @didaquis  quizá te ayuden estos dos enlaces en los que he escrito al respecto:
- https://medium.com/@CKGrafico/taking-decisions-to-structure-big-projects-with-hooks-stores-services-and-more-a703c7874480
- boilerplates.js.org

**Comment by nucliweb** [comment]
Muchas gracias @CKGrafico por tu aportación 😊

**Comment by didaquis** [comment]
> quizá te ayuden estos dos enlaces en los que he escrito al respecto

Lo investigo! Gracias
